### ISSUE TITLE
implement polling

### ISSUE THREAD

**Issue by flying-sheep** [snoweye/pbdZMQ#23]
we’d like to replace rzmq with this, but there are no polling capabilities.

like [here](https://github.com/zeromq/pyzmq/blob/768836c93a07c29623da16d511301caae34906c3/zmq/backend/cython/_poll.pyx) or [here](https://github.com/armstrtw/rzmq/blob/master/src/interface.cpp#L217)

**Comment by snoweye** [comment]
Is this the only wish? Or, is there any other more? If this were not in an emergency, it would be there when I got time. pbdR has others have to go. By the way, I have no idea about python nor C++, so the implementations are all done by my understanding. If you can explain what your application does, that may help me to figure out what polling is.

**Comment by flying-sheep** [comment]
> Is this the only wish? Or, is there any other more?

i think we also use multipart messages (`receive.multipart` and `send.multipart` in rzmq), but those are trivial to do:

``` r
zmq.send.multipart <- function(parts, socket) {
    for (part in parts[1:(length(parts) - 1)]) {
        zmq.send.raw(part, socket, .pbd_env$ZMQ.SR$SNDMORE)
    }
    zmq.send.raw(parts[[length(parts)]], socket, .pbd_env$ZMQ.SR$BLOCK)
}
```

> If this were not in an emergency, it would be there when I got time. pbdR has others have to go.

well, as of now, pyzmq does its job, we just think this project (with good binary packages being hosted on CRAN and all) would save us many tech support bugreports about mismatching .so versions and stuff like that.

> If you can explain what your application does, that may help me to figure out what polling is.

[polling is described here](http://api.zeromq.org/2-1:zmq-poll)

**Comment by snoweye** [comment]
Probably done. Please see new push for updates. Let me know if any bug is found.

**Comment by flying-sheep** [comment]
hi, the first bug is that “zmq.recv.multipart” returns a list of raw vectors that don’t have the correct length.

e.g. instead of the bytes for `'<IDS|MSG>'`, it returns`'<IDS|MSG>\003\0\002\003\0...` (i.e. a buffer full of garbage)

i think it should just use `zmq.msg.recv`.

**Comment by snoweye** [comment]
A reproducible example will be helpful, please.

Yes, I had zmq.msg.send and zmq.msg.recv to replace multipart when messages are short.

**Comment by flying-sheep** [comment]
the version that works for me is [this one](https://github.com/IRkernel/IRkernel/blob/pbd-zmq/R/kernel.r#L11-L25). it simply uses `zmq.msg.recv`-

**Comment by snoweye** [comment]
Now I know what you mean. recv by default allocates 1024 bytes (bits?), so the tail is very probably not truncated. I change to msg.recv that is a better way to deal with the problem. Let me know if there is more bugs.

**Comment by flying-sheep** [comment]
great. thanks!
