### ISSUE TITLE
Release on CRAN

### ISSUE THREAD

**Issue by rgbkrk** [snoweye/pbdZMQ#24]
Any possibility of releasing this on CRAN?

Even cooler if you release pre-built binaries. :wink:

/cc https://github.com/IRkernel/IRkernel/pull/238 @flying-sheep @JanSchulz @takluyver

**Comment by wrathematics** [comment]
I think @snoweye is waiting on me.  We got into a situation where some of my downstream stuff needed upstream changes, and I'm still poking at things.  We should be ready very soon, within a day or so.

We also have been toying with the idea of shipping binaries for Linux, probably for Ubuntu via PPA.  That what you had in mind?

**Comment by snoweye** [comment]
Please give wrathematics a few days. I will let you know when the CRAN is updated. We have 8 pbd packages need to be on CRAN very shortly. I think ZMQ is an easy one. There will be binary for Windows and Mac on CRAN. The Linux version will check if a system libzmq were available via pkg-config, then chenck if a user provided libzmq were available via --configure-vars. If non of them were found, then an internal shipped libzmq would be compiled. So, there is no need for binary on Linux. Anyway, PPA is next for sure.

**Comment by rgbkrk** [comment]
Awesome. Plenty of time. We're looking forward to switching over to your bindings for IRKernel.

**Comment by flying-sheep** [comment]
@wrathematics @snoweye any status update? things going well? :smile:

**Comment by snoweye** [comment]
On CRAN now. There are more downstream work than we expect, but anyway here you are.

**Comment by flying-sheep** [comment]
grreat! thank you!

**Comment by rgbkrk** [comment]
:tada: Thank you all! :tada:

**Comment by QuLogic** [comment]
Please add a tag for the commit that was released on CRAN.
