### ISSUE TITLE
Internal ZMQ install path doesn’t work as described

### ISSUE THREAD

**Issue by flying-sheep** [snoweye/pbdZMQ#27]
Hi, I tried this:

``` r
R CMD INSTALL pbdZMQ_0.2-0.tar.gz --configure-args="--enable-internal-zmq"
```

but it didn’t work:

```
checking whether the C compiler works... no
configure: error: in `$tmp/pbdZMQ/src/zmqsrc':
configure: error: C compiler cannot create executables
See `config.log' for more details
make[1]: Entering directory `$tmp/pbdZMQ/src/zmqsrc/src'
make[1]: *** No rule to make target `all'.  Stop.
make[1]: Leaving directory `$tmp/pbdZMQ/src/zmqsrc/src'
make[1]: Entering directory `$tmp/pbdZMQ/src/zmqsrc/src'
make[1]: *** No rule to make target `install'.  Stop.
make[1]: Leaving directory `$tmp/pbdZMQ/src/zmqsrc/src'
make: *** [libzmq] Error 2
ERROR: compilation failed for package ‘pbdZMQ’
* removing ‘$tmp/pbdZMQ’
      -----------------------------------
ERROR: package installation failed
```

**Comment by snoweye** [comment]
- Can you check what config.log says?
- To me, "checking whether the C compiler works... no" means your gcc probably off or no permission to write where being installed ...

**Comment by flying-sheep** [comment]
[here it is](https://gist.github.com/flying-sheep/8f691b0a7718648846b9c2737071e073).

**Comment by snoweye** [comment]
- Sorry, to be clear, I meant the one(s) at `$tmp/pbdZMQ/src/zmqsrc/src` or `$tmp/pbdZMQ/src/zmqsrc/`.
- There is no problem with the one you gave, otherwise it didn't reach internal library.
- Please check them again. Thanks. 
- It will be easier for you to get if you can `tar zxvf` the package first. Then install the directory with
  `R CMD INSTALL pbdZMQ --configure-args="...."`

**Comment by flying-sheep** [comment]
ah! there is one too, i’m dumb. the relevant section:

``` c
configure:3751: gcc -m64 -v >&5
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.3/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-isl=/builddir/build/BUILD/gcc-4.8.3-20140911/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.3-20140911/obj-x86_64-redhat-linux/cloog-install --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.3 20140911 (Red Hat 4.8.3-7) (GCC) 
configure:3762: $? = 0
configure:3751: gcc -m64 -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:3762: $? = 4
configure:3751: gcc -m64 -qversion >&5
gcc: error: unrecognized command line option '-qversion'
gcc: fatal error: no input files
compilation terminated.
configure:3762: $? = 4
configure:3782: checking whether the C compiler works
configure:3804: gcc -m64  -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 recordcc-switches  -m64 -mtune=generic  -I/usr/local/include -Wl,-z,relro  conftest.c  >&5
gcc: error: recordcc-switches: No such file or directory
configure:3808: $? = 1
configure:3846: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "zeromq"
| #define PACKAGE_TARNAME "zeromq"
| #define PACKAGE_VERSION "4.1.0"
| #define PACKAGE_STRING "zeromq 4.1.0"
| #define PACKAGE_BUGREPORT "zeromq-dev@lists.zeromq.org"
| #define PACKAGE_URL ""
| #define PACKAGE "zeromq"
| #define VERSION "4.1.0"
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:3851: error: in ‘/home/icb/philipp.angerer/pbdZMQ-master/src/zmqsrc’:
configure:3853: error: C compiler cannot create executables
```

**Comment by snoweye** [comment]
- It  looks like your Red Hat gcc did not take certain options like `-V`, `-qversion`, or `recordcc-switches`?
- Is this the only compiler you have? Or, are some other libraries missing possibly?
- ... hit a wrong button.

**Comment by flying-sheep** [comment]
hmm, is it normal that recordcc-switches is passed bare like that?

`... --param=ssp-buffer-size=4 recordcc-switches ...` looks like it’s in a file position. shouldn’t it be `-frecordcc-switches`?

also the trying of multiple version switches make me think that only one has to do something (the build doesn’t fail after that and, yeah, it tries, multiple)

and i think i only have gcc on that machine. is it really so old that it can’t work?

**Comment by snoweye** [comment]
- Not so sure about anything yet, but I found
  `https://github.com/mapnik/python-mapnik/issues/54`
- Please see if this help. `-g` is missing probably.

**Comment by flying-sheep** [comment]
where do i add -g? in the Makevars.in somewhere?

**Comment by snoweye** [comment]
- Try the `libicu-devel` solution first.
- Yes, but this can mess up other platform. I have my two tests Cent and Ubuntu without any problem. I am not sure why Red Hat has this trouble.

**Comment by flying-sheep** [comment]
it’s actually Fedora 20 :neutral_face: 

removing `-e "s/-g//g"` [here](https://github.com/snoweye/pbdZMQ/blob/b82b6741af26c13e506cc55902d953509a1e5562/src/build_zmq.in#L4) helped. then it got to

``` gcc
/usr/include/features.h:327:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
 #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
    ^
cc1plus: all warnings being treated as errors
```

i removed the last `-e ...` from the removeFlags function and it compiles!

**Comment by flying-sheep** [comment]
i doubt the libicu thing has anything to do with an old GCC version complaining about flags, i bet that was simply a library that person in the other thread missed

**Comment by flying-sheep** [comment]
thanks!

is there a chance we can identify which GCC function need those flags to be preserved and retain them there?

**Comment by snoweye** [comment]
Thanks.
- There are some typos made at
  https://github.com/snoweye/pbdZMQ/commit/fd58a10f72cf08f6f7eb5927bb7856cba3e7b50a
- Please check if the fix works. That was intended to remove `-g` for disabling debugging builds.
- I tried to minimize changes to the original ...

**Comment by flying-sheep** [comment]
sorry: removing some sed expressions helped me:

``` diff
-  sed -e "s/-g//g" -e "s/-f[Pp][Ii][Cc] //" -e "s/-w //" -e "s/-O\?[0-9] //" $1
+  sed              -e "s/-f[Pp][Ii][Cc] //" -e "s/-w //"                     $1
```

**Comment by snoweye** [comment]
Since I don't need to worry about Solaris now, so this is good to me too.
