### ISSUE TITLE
Broken Mac OS X package on CRAN?

### ISSUE THREAD

**Issue by jankatins** [snoweye/pbdZMQ#28]
This is the result of installing irkernel on a Mac OS X R3.3 system:

```
* installing *source* package ‘IRkernel’ ...
** R
** inst
** preparing package for lazy loading
Error : .onLoad failed in loadNamespace() for 'pbdZMQ', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: nie można załadować współdzielonego obiektu  '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/pbdZMQ/libs/pbdZMQ.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.3/Resources/library/pbdZMQ/libs/pbdZMQ.so, 6): Library not loaded: /Builds/CRAN-QA-Simon/packages/mavericks-x86_64/Rlib/3.3/pbdZMQ/libs/libzmq.4.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.3/Resources/library/pbdZMQ/libs/pbdZMQ.so
  Reason: image not found
ERROR: lazy loading failed for package ‘IRkernel’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/IRkernel’
BŁĄD: Command failed (1)
```

IMO the line which tries to load the wrong libzmq.4.dylib shows that it is not finding the included libzmq.dylib.

This is https://github.com/IRkernel/IRkernel/issues/303 and https://github.com/IRkernel/IRkernel/pull/330 in the IRkernel repo...

**Comment by snoweye** [comment]
- Can you try one thing for me? Please install from source (.tar.gz) and see if this fails as well.
- I guess you install the binary from CRAN, right?
- `Library not loaded: /Builds/CRAN-QA-Simon/packages/mavericks-x86_64/Rlib/3.3/pbdZMQ/libs/libzmq.4.dylib`
- The one on CRAN did not install to the common place ... See if the FAQ 7.1 of pbdZMQ vignette solves the problem at `https://github.com/snoweye/pbdZMQ/blob/master/inst/doc/pbdZMQ-guide.pdf`.
- Seems no problem to me at `https://travis-ci.org/snoweye/pbdZMQ/jobs/131009685`.
- I will try to overwrite the `pbdZMQ.so` at run-time but this can take a while to test and fix.

**Comment by snoweye** [comment]
- I add the run-time overwriting to zzz.r.in for OS X, so it will get the internal one when it runs.
- OS X use rpath(?) to manage linking of dynamic libraries. So when pbdZMQ.so is built, it has been register a rpath to libzmq.4.dylib or libzmq.a (maybe). There is nothing wrong here.
- However, R prebuilds packages at some tmp directory, then install to where it should be installed. I already has `build_zmq.in' to overwrite the prebuilt one to the installed path. However, ...
- In your example, Simon (CRAN OS X maintainer?) installs it to an uncommon directory, then build the binary file from it.
- If users don't install the binary file at the same directory, then pbdZMQ.so will not possible to find the libzmq.4.dylib.
- This is why ZMQ guys want to use ldconfig or so to set the library path at run-time.
- Please try the current github version. It should work as shown at `https://travis-ci.org/snoweye/pbdZMQ`. Let me know if there is any problem. If not, I will send the fixes to CRAN.

**Comment by flying-sheep** [comment]
the problem occurred for @gacek91

neither @janschulz nor @takluyver or me have a mac so @gacek91 needs to do those things.

**Comment by jankatins** [comment]
IMO the easiest way would be if pbdZMQ would simply statically link to a included version of the library (by first building a static version from the included zmq source).

**Comment by flying-sheep** [comment]
you can do it but the default is to link against system libZMQ. which is a sane behavior generally.

i _want_ things to be linked dynamically here on linux.

**Comment by jankatins** [comment]
The problem is that there is no system libzmq on both windows and macosx :-( 

IMO: only things installed by the same package manager should be dynamically linked against unless the lib is generally "just there" (e.g. the "manylinux" python wheels which uses the most common libs on different linux systems...).

Can you guarantee that libZMQ is installed on a new ubuntu system where R is installed and now a `install.packages("pbdZMQ")` is run?

**Comment by takluyver** [comment]
> Can you guarantee that libZMQ is installed on a new ubuntu system where...

AFAIK, no, ZMQ is not guaranteed to be installed. There are also two versions of libzmq packaged for Ubuntu, just to add further confusion.

I'm inclined to agree with you that dynamic linking is tricky unless a single package manager can keep track of the dependency between the two parts.

**Comment by flying-sheep** [comment]
pbdZMQ of course only uses the installed one if it exists.

**Comment by snoweye** [comment]
- It was built in static internally once, but for some reasons dynamic is easier for most platforms including OS X.
- The trouble here is how OS X managing their dynamic libraries ... where `pbdZMQ.so` should be linked to is not a problem because `*.so` on OS X are still dynamic and need to follow what them have to be. I am not sure static will make the trouble goes away.
- I can try but this will take much longer to have all platforms happy. I believe current one should work on OS X if anyone can test it. I did test on Travis without your `IRkernel`. I tried `IRkernel` on Traivs, but have no idea what it needs for the fails of building it.
- The reasons were at `https://github.com/snoweye/pbdZMQ/blob/master/ChangeLog#L143-L147`. Those IO related functions are not acceptable by CRAN ... The static library will bring those into `pbdZMQ.so` and can be caught by `R CMD check`.
- Please try from your OS X clients and see if they make the current change work.

**Comment by flying-sheep** [comment]
it usually does work! we have far fewer people with problems. thank you for your work!

**Comment by jankatins** [comment]
Just for your information: using the github version on TRAVIS works: https://travis-ci.org/IRkernel/IRkernel/builds/131386915

**Comment by snoweye** [comment]
Thanks. This is great. I will send the current version to CRAN and let you know when OS X binary is built which can take a few days. This will be the last test for the issue.

**Comment by ashkan25** [comment]
I had the same result when trying to install irkernel on OSX R3.3. Installing pbdZMQ from the dev tools package seem to have fixed the issue for me.

**Comment by snoweye** [comment]
Version 0.2-3 for OS X binaries have been built for R-3.3 and R-devel on CRAN now. Please check and see if this issue goes away. Thanks.

**Comment by jankatins** [comment]
Trying it out now on travis :-)

**Comment by jankatins** [comment]
and it worked :-) Will there be 3.2 packages?

**Comment by snoweye** [comment]
Thanks.
I think the binary for 3.2 is on CRAN as well.
OS X Mavericks binaries:    r-release: pbdZMQ_0.2-3.tgz, r-oldrel: pbdZMQ_0.2-3.tgz

**Comment by jankatins** [comment]
It anyway doesn't matter: travis always uses the latest release :-( https://github.com/travis-ci/travis-ci/issues/6092
