### ISSUE TITLE
Why does taskvent.r sleep between tasks?

### ISSUE THREAD

**Issue by rstub** [snoweye/pbdZMQ#34]
With `taskvent.r`, `tasksink.r` and `taskwork.r` you provide an implementation of the parallel pipeline pattern from http://zguide.zeromq.org/page:all#Divide-and-Conquer. I am wondering about the this sleep here: https://github.com/snoweye/pbdZMQ/blob/master/demo/taskvent.r#L29. As is, this is the main task of the program, defeating the purpose of parallel processing. If I comment out this line, all tasks are process by only one worker. Any idea what is going on here?

**Comment by snoweye** [comment]
An example is what that for.
