### ISSUE TITLE
Does ls wrapper in R/base_ls.r need to be exported?

### ISSUE THREAD

**Issue by wrathematics** [snoweye/pbdZMQ#35]
I'm not sure I understand why this exists (is it for the control calls?). But does it need to be exported?

**Comment by snoweye** [comment]
FYI.
[To get rid of similar problems such as this](https://github.com/IRkernel/IRkernel/issues/426).

**Comment by ghost** [comment]
> FYI. [To get rid of similar problems such as this](https://github.com/IRkernel/IRkernel/issues/426).

It looks the bug is still there. See [here](https://github.com/IRkernel/IRkernel/issues/726).
