### ISSUE TITLE
Missing autotools m4 file?

### ISSUE THREAD

**Issue by mingwandroid** [snoweye/pbdZMQ#53]
I'm trying to make a fix to `pbdZMQ` that requires changing `configure.ac`, however I cannot run `autoconf` afterwards due to an apparent missing m4 file:

https://github.com/snoweye/pbdZMQ/blob/master/configure.ac#L31

**Comment by snoweye** [comment]
I add the m4 file back. Please check if it helps.

**Comment by mingwandroid** [comment]
Yes, it's good that it is back, thanks.
