### ISSUE TITLE
"R_zmq_recv_file" not available for .Call() for package "pbdZMQ"

### ISSUE THREAD

**Issue by VictorYammouni** [snoweye/pbdZMQ#56]
Hello

I'm trying zmq.recvfile and zmq.sendfile functions as described in the help, but I get the following error:

"R_zmq_recv_file" not available for .Call() for package "pbdZMQ"

is the file transfer implemented?

Thank's

**Comment by wrathematics** [comment]
It was an R packaging issue. I've fixed it in this PR https://github.com/snoweye/pbdZMQ/pull/57

**Comment by snoweye** [comment]
Merged now, thanks.
