### ISSUE TITLE
signed/unsigned integer comparison

### ISSUE THREAD

**Issue by wrathematics** [snoweye/pbdZMQ#58]
In `src/shellexec_wcc.c, there is a signed/unsigned integer comparison:

https://github.com/snoweye/pbdZMQ/blob/master/src/shellexec_wcc.c#L65

```c
	size_t inb, outb, res;
// ...
	if(res == -1) warning("file name conversion problem");
```

Should that be `(size_t) -1` / `SIZE_MAX` (defined in `stdint.h`), or is the check completely spurious, or something else?

**Comment by snoweye** [comment]
It should be `res == (size_t) -1` inside the `if(...)` check. It returns as an indicator for the error. max length should be already taken cared by the line 64. It is a direct copy of R source. You may change it if there is any compiling issue, otherwise I would not to bother it.

**Comment by wrathematics** [comment]
Ahh, ok. Thanks.
