### ISSUE TITLE
Provide a ZeroMQ library by default?

### ISSUE THREAD

**Issue by mschubert** [snoweye/pbdZMQ#63]
Hi,

I am the author of the [`clustermq`](https://github.com/mschubert/clustermq) package, for which I would like to (1) simplify the install process for users by not requiring ZeroMQ externally and (2) move some network logic to compiled code.

`pbdZMQ` already solves (1), but as far as I can tell I can not use `LinkingTo: pbdZMQ` because the actual ZeroMQ library might either reside in the package or on the system (and the actual library symbols are not defined in the pbdZMQ .so file).

I'm wondering if it makes sense instead of using either the system or internal ZeroMQ library to always distribute the library with this package. As far as I can tell, this would also have a couple of advantages:

* Other R packages could link to the ZeroMQ library in this package
* The package would use a defined version of the library
* The install process of this package could be simplified by not checking for the system library

The only downside is that the package would get bigger, but the ZeroMQ .so is only 500-600 kb (which I do not think is a big issue).

Do you have any thoughts on this?

**Comment by snoweye** [comment]
- [Juniper](https://github.com/JuniperKernel/JuniperKernel) had been explicitly linking with libzmq shared library provided in pbdZMQ internally and externally depending on how pbdZMQ was installed.
- [IRkernel](https://github.com/IRkernel/IRkernel) also uses zmq functions in R through pbdZMQ.
- [remoter](https://github.com/RBigData/remoter) has a fully implemented client/server framework built on top of pbdZMQ and ZMQ.
- All are on CRAN for a while now and built and checked for most platforms.

**Comment by wrathematics** [comment]
I think you just need `pbdZMQ::get.zmq.cppflags()` and `pbdZMQ::get.zmq.ldflags()` to reliably build against it. The JuniperKernel package finds these in their configure script: https://github.com/JuniperKernel/JuniperKernel/blob/master/configure

**Comment by mschubert** [comment]
Thank you both!

@wrathematics This is excellent, looks like this solves my issue exactly :+1:
