### ISSUE TITLE
stack smashing in zmq.msg.recv

### ISSUE THREAD

**Issue by flying-sheep** [snoweye/pbdZMQ#64]
Trying to run IRkernel on a fedora 28 system, I get a crash [on this line](https://github.com/IRkernel/IRkernel/blob/a33d672ff7f5f128bd1773b5064036a20cc28f91/R/kernel.r#L13) or [on this line](https://github.com/IRkernel/IRkernel/blob/a33d672ff7f5f128bd1773b5064036a20cc28f91/R/kernel.r#L109). The trace is either:

```
Tracing kernel$run() on entry 
Tracing zmq.poll.get.revents(1) on entry 
Tracing hb_reply() on entry 
Tracing zmq.msg.recv(sockets$hb, unserialize = FALSE) on entry 
*** stack smashing detected ***: <unknown> terminated
```
or
```
Tracing kernel$run() on entry 
Tracing zmq.poll.get.revents(1) on entry 
Tracing zmq.poll.get.revents(2) on entry 
Tracing handle_shell() on entry 
Tracing zmq.recv.multipart(sockets$shell, unserialize = FALSE) on entry 
Tracing zmq.msg.recv(socket, flags = .pbd_env$ZMQ.SR$BLOCK, unserialize = unserialize) on entry 
*** stack smashing detected ***: <unknown> terminated
```

My system libzmq is version 5.

<details>
<summary>ldd output</summary>

```console
$ ldd .local/lib/R/3.5/pbdZMQ/libs/pbdZMQ.so
        linux-vdso.so.1 (0x00007fffb3bd9000)
        libzmq.so.5 => /lib64/libzmq.so.5 (0x00007f058e01c000)
        libR.so => /usr/lib64/R/lib/libR.so (0x00007f058d9a3000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f058d5e4000)
        libpgm-5.2.so.0 => /lib64/libpgm-5.2.so.0 (0x00007f058d397000)
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f058d148000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f058cf40000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f058cd21000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f058c98f000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f058c5fb000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f058c3e3000)
        libRblas.so => /usr/lib64/R/lib/libRblas.so (0x00007f058952e000)
        libgfortran.so.5 => /lib64/libgfortran.so.5 (0x00007f05890b3000)
        libquadmath.so.0 => /lib64/libquadmath.so.0 (0x00007f0588e73000)
        libreadline.so.7 => /lib64/libreadline.so.7 (0x00007f0588c26000)
        libtre.so.5 => /lib64/libtre.so.5 (0x00007f0588a15000)
        libpcre2-8.so.0 => /lib64/libpcre2-8.so.0 (0x00007f0588795000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f0588524000)
        liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f05882fd000)
        libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f05880ec000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f0587ed5000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f0587cd1000)
        libicuuc.so.60 => /lib64/libicuuc.so.60 (0x00007f058790f000)
        libicui18n.so.60 => /lib64/libicui18n.so.60 (0x00007f0587450000)
        libgomp.so.1 => /lib64/libgomp.so.1 (0x00007f0587220000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f058e4fe000)
        libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f0586f33000)
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f0586d17000)
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f0586b13000)
        libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f0586904000)
        libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007f0586478000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f0586274000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f058605d000)
        libtinfo.so.6 => /lib64/libtinfo.so.6 (0x00007f0585e30000)
        libicudata.so.60 => /lib64/libicudata.so.60 (0x00007f0584287000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f058405e000)
```

</details>

**Comment by flying-sheep** [comment]
I tried and it works well with the internal ZMQ! 

```shell
git clone https://github.com/snoweye/pbdZMQ.git
cd pbdZMQ
./configure --enable-internal-zmq
R CMD INSTALL --no-configure .
```

Are you not supporting libzmq 5? If so, could you please enable the internal lib if the system libZMQ is version 5?

Also i compiled it with R 3.5 and it seems to work fine. Are you sure you needed to go all the way from requiring R 3.2 to R 3.6 in f964668063d9e3692bccb40d609acf2f0f1fd016?

**Comment by snoweye** [comment]
- What is the version of ZMQ in the `lib64/libzmq.so.5`? 4.3.1 or 4.2.3? I can try to ignore it from `configure.ac` temporarily. If it links well, I don't think the support should be an issue unless there is changes to how they handle the calls that may due to compilers. 
- I can roll back to 3.5, but 3.6 or higher should be the future even 3.6 has a lot of issues. The change to 3.6 was due to other requests from CRAN.

**Comment by flying-sheep** [comment]
4.1.6:

```console
$ dnf provides /usr/lib64/libzmq.so.5.0.2
…
zeromq-4.1.6-7.fc28.x86_64 : Software library for fast, message-based applications
…
```

**Comment by flying-sheep** [comment]
regarding the R version: CentOS 7 has R 3.5 so I think that’s a good target if one doesn’t *need* 3.6 features. (and I didn’t see many changes in the NEWS file that seem relevant to a backend package like pbdZMQ)

**Comment by snoweye** [comment]
- I roll back it to 3.5.0.
- What do you get from `pbdZMQ::zmq.version()` when it links with `libzmq.so.5.0.2`? `4.1.6`? Hmm... would that be bugs in the old version?
- Internal version is `4.2.2`. I do have `4.3.1` that is in `libzmq.so.5.2.1` (manually installed not from binary repo).
- Can you create a simple buggy code that I can test it? I don't have python or any kernel installed, but I can try. 
- Move to 3.6 was completely due to CRAN installation and their other check ...

**Comment by flying-sheep** [comment]
> Can you create a simple buggy code that I can test it?

Sorry, I’m really busy with my thesis. This should work:

```bash
pip3 install jupyterlab
R --slave -e 'install.packages("IRkernel"); IRkernel::installspec()'
jupter console --kernel=ir
```

**Comment by snoweye** [comment]
I have `apt-get` to install `libzmq3-dev` and `libzmq5` on Ubuntu, but both have version `4.3.1`. So, I may not be able to test `IRkernel` with right version. This can take very long time. When is your thesis due?
- I have blocked version 4.1.6 from [here](https://github.com/snoweye/pbdZMQ/blob/master/configure.ac#L39-L44), so please check it again.
- Then, make sure the "zmq.h" has the same version as "libzmq.so*". My `libzmq5` did not have a header file.

**Comment by flying-sheep** [comment]
It matches:

```console
$ grep '#define ZMQ_VERSION_.*' /usr/include/zmq.h
#define ZMQ_VERSION_MAJOR 4
#define ZMQ_VERSION_MINOR 1
#define ZMQ_VERSION_PATCH 6
```

**Comment by snoweye** [comment]
Thanks.
