### ISSUE TITLE
Fail to install pbdZMQ

### ISSUE THREAD

**Issue by jmercier-lbi** [snoweye/pbdZMQ#66]
While I try to install pbdZMQ_0.3-3.tar.gz on centos 7 the build works fine
The problem come at installation step:

```bash
r-3.6.0: /usr/bin/mkdir -p '/tmp/jmercier-reforge/BUILDROOT/tmp/RtmppKnSp9/R.INSTALL31192ef5f549/pbdZMQ/src/zmq/include'
r-3.6.0: /usr/bin/install -c -m 644 include/zmq.h include/zmq_utils.h include/zmq.hpp include/zmq_addon.hpp '/tmp/jmercier-reforge/BUILDROOT/tmp/RtmppKnSp9/R.INSTALL31192ef5f549/pbdZMQ/src/zmq/include'
r-3.6.0: /usr/bin/mkdir -p '/tmp/jmercier-reforge/BUILDROOT/tmp/RtmppKnSp9/R.INSTALL31192ef5f549/pbdZMQ/src/zmq/lib/pkgconfig'
r-3.6.0: /usr/bin/install -c -m 644 src/libzmq.pc '/tmp/jmercier-reforge/BUILDROOT/tmp/RtmppKnSp9/R.INSTALL31192ef5f549/pbdZMQ/src/zmq/lib/pkgconfig'
r-3.6.0: make[3]: Leaving directory `/tmp/RtmppKnSp9/R.INSTALL31192ef5f549/pbdZMQ/src/zmqsrc'
r-3.6.0: make[2]: Leaving directory `/tmp/RtmppKnSp9/R.INSTALL31192ef5f549/pbdZMQ/src/zmqsrc'
r-3.6.0: make[1]: Leaving directory `/tmp/RtmppKnSp9/R.INSTALL31192ef5f549/pbdZMQ/src/zmqsrc'
r-3.6.0: mv ./zmqsrc/Makefile ./zmqsrc/Makefile.done
r-3.6.0: # ( cp ./zmq/lib/libzmq.so ./libzmq.so )
r-3.6.0: ( cp ./zmq/lib/libzmq* ./ )
r-3.6.0: cp: cannot stat ‘./zmq/lib/libzmq*’: No such file or directory
r-3.6.0: make: *** [libzmq] Error 1
r-3.6.0: ERROR: compilation failed for package ‘pbdZMQ’
```

**Comment by snoweye** [comment]
How did you install the package? @jmercier-lbi 

My "R CMD INSTALL" and "install.packages()" are both fine as below.

R> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] pbdZMQ_0.3-3

loaded via a namespace (and not attached):
[1] compiler_3.6.0 tools_3.6.0    tcltk_3.6.0

**Comment by jmercier-lbi** [comment]
Hi @snoweye 

We have found the reason to this fail. In fact in HPC we use a tools named [module ](https://github.com/cea-hpc/modules)in order to own multiple version of the same tools (deb and rpm cannot do this) . So we have build `R` with a gcc release more recent that can be provided by the OS. 
1/ R start 
2/ it detect the gcc used to build itself
3/ path exists 
4/ build start but ...
it use the gcc provided by the system

The tools should use the same gcc used to build `R` . This gcc can to be  different to the one provided by the system

the workaround was to load the same gcc used to build R

```
module load gcc/8.3.0
```

**Comment by snoweye** [comment]
Thanks.
