### ISSUE TITLE
pbdZMQ will not install with g++ 8.3.1

### ISSUE THREAD

**Issue by mathog** [snoweye/pbdZMQ#70]
g++ 8.3.1 on CentOS 8 flags an error in pbdZMQ and halts installation:

```
  CXX      src/src_libzmq_la-msg.lo
In member function 'int zmq::msg_t::set_group(const char*, size_t)',
    inlined from 'int zmq::msg_t::set_group(const char*)' at src/msg.cpp:549:22:
src/msg.cpp:560:13: error: 'char* strncpy(char*, const char*, size_t)' output truncated before terminating nul copying as many bytes from a string as its length [-Werror=stringop-truncation]
     strncpy (u.base.group, group_, length_);
     ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/msg.cpp: In member function 'int zmq::msg_t::set_group(const char*)':
src/msg.cpp:549:22: note: length computed here
     return set_group (group_, strlen (group_));

```

I have not checked the code but that error usually results when the length parameter is the same size or larger than the destination buffer.  This does not leave room ASCII Nul string terminator.

**Comment by mathog** [comment]
Change line 561 of msg.cpp from

`    strncpy (u.base.group, group_, length_);
`
to

`    strncpy (u.base.group, group_, length_ - 1);
`
and it will compile and install.  I don't know exactly what the set_group method is doing though, so perhaps that is not the proper fix.

**Comment by snoweye** [comment]
Fixed. Thanks.
