### ISSUE TITLE
Force linking with clang++

### ISSUE THREAD

**Issue by jeroen** [snoweye/pbdZMQ#76]
The cross compilation fails on r-universe: https://github.com/r-universe/snoweye/actions/runs/7494400310/job/20402312521

The problem is the package is linked with `clang` instead of `clang++` because you don't have any c++ files in the package, however libzmq does need to be linked with clang++.

This case is described in [WRE 5.6.1 ](https://cran.r-project.org/doc/manuals/R-exts.html):

> Even fewer external libraries use C++ internally but present a C interface, such as [rgeos](https://cran.r-project.org/package=rgeos). These require the C++ runtime library to be linked into the package’s shared object/DLL, and this is best done by including a dummy C++ file in the package sources.

So you can probably fix this problem by creating an empty `src/dummy.cc` similar like https://github.com/cran/rgeos/blob/master/src/dummy.cc

**Comment by snoweye** [comment]
I don't have MacOS. Would you mind checking whether [this update](https://github.com/snoweye/pbdZMQ/commit/e240a31a2daf9068b3b43a34ade3af4a535e025c) working or not? @jeroen

**Comment by jeroen** [comment]
Yes it is fixed. Binaries are now available at: https://snoweye.r-universe.dev/pbdZMQ
