### ISSUE TITLE
Documentation overhaul

### ISSUE THREAD

**Issue by wrathematics** [snoweye/pbdZMQ#9]
I would like to overhaul the documentation.  The short version of what I am proposing is:
- (almost) every function gets its own help file (e.g., `zmq.bind()`, `zmq.connect()`, ...)
- Each low-level function has a ZeroMQ API added to the help under `@references` (e.g., `zmq.bind()` gets http://api.zeromq.org/2-1:zmq-bind added as a reference).

Practically speaking, this would require abandoning the current .Rd file naming structure.  I'm willing to do this, but if you have strong reservations against the change, maybe we could talk about it further over email?

**Comment by snoweye** [comment]
ok
